language: go

# github.com/flynn/hid is broken on go1.12 on MacOS X, so pin to go1.11.x
go:
    - 1.13.x

os:
    - linux
    - osx

before_install:
    - go get github.com/mattn/goveralls
    - REPO_NAME=$(basename $PWD)
    - GITHUB_PATH=$(dirname $(dirname $PWD))
    - CF_PROJECT_DIR=${GITHUB_PATH}/Cloud-Foundations/${REPO_NAME}
    - mkdir -p ${CF_PROJECT_DIR}
    - rsync -az ${TRAVIS_BUILD_DIR}/ ${CF_PROJECT_DIR}/
    - export TRAVIS_BUILD_DIR=${CF_PROJECT_DIR}
    - cd ${CF_PROJECT_DIR}

install: make get-deps

script:
    - go test -v -covermode=count -coverprofile=coverage.out ./...
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
    - make all test
